name: frontend
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  markdown: ^7.2.2
  web: ^0.4.2
  web_socket_channel: ^2.4.3
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.8
  build_test: ^2.2.2
  build_web_compilers: ^4.0.9
  lints: ^2.1.0
